version: 2.1

jobs:
  build:
    docker:
      - image: 'ubuntu:latest'
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: ./install-dependencies.sh
      - run:
          name: Build project
          command: CC=clang CXX=clang++ ./build.sh
          no_output_timeout: 60m
      - sonarcloud/scan


orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
